version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
      time: "12:26"
      timezone: "Europe/Vienna"
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
      time: "12:26"
      timezone: "Europe/Vienna"
